import * as THREE from 'three';
import {Stage} from '../../../src/render/stage';
import {SheetView} from '../../../src/render/sheetView';
import {makePaperTextures} from '../../../src/render/textures';
import {findPaper} from '../../../src/papers';
import {buildTimeline,evaluateFrame} from '../../../src/fold/timeline';
import {buildCrossFrontRobe} from './crossFrontRobeStudy';
import {buildDress} from '../../../src/fold/construction';
import {buildJacket} from '../../../src/fold/jacket';
const p = new URLSearchParams(location.search);
const c = p.get('design') === 'dress' ? buildDress() : p.get('design') === 'jacket' ? buildJacket() : buildCrossFrontRobe();
const stage=new Stage(document.querySelector('canvas')!);stage.resize();
const fm=new THREE.MeshStandardMaterial({roughness:.9}),bm=fm.clone();
const paper=p.get('paper')==='plain'?{id:'plain',name:'Plain two-sided',note:'',reverse:'#d1c4a4',drawFront(ctx:CanvasRenderingContext2D,s:number){ctx.fillStyle='#355f70';ctx.fillRect(0,0,s,s)},drawBack(ctx:CanvasRenderingContext2D,s:number){ctx.fillStyle='#d1c4a4';ctx.fillRect(0,0,s,s)}}:findPaper(p.get('paper'));
const textures=makePaperTextures(paper,Number(p.get('turn')||0),stage.renderer.capabilities.getMaxAnisotropy());fm.map=textures.front;bm.map=textures.back;
const sheet=new SheetView(fm,bm),tl=buildTimeline(c.ops);let op=tl.ops[tl.ops.length-1];const step=Number(p.get('step'));if(p.has('step'))op=tl.ops[step];sheet.setAnim(op);sheet.pose(evaluateFrame(op,p.has('progress')?Number(p.get('progress')):1));stage.modelRoot.add(sheet.group);
stage.modelRoot.rotation.x=0;stage.modelRoot.position.y=1.05;
stage.backLight.intensity=.8;
const angle=p.get('view')==='back'?Math.PI:p.get('view')==='angle'?.24*Math.PI:0;
const target=new THREE.Vector3(0,1.05,0),d=stage.fitDistance(1.1,1.1);stage.placeCamera(target.clone().add(new THREE.Vector3(Math.sin(angle)*d,.12*d,Math.cos(angle)*d)),target);
document.getElementById('label')!.textContent=c.name+' · '+paper.name+' · '+(p.get('view')||'front');
stage.render();(window as any).studyReady=true;
